name = "JPerplex"
uuid = "47cd544e-370f-4714-8b6c-e3a83d4a5076"
authors = ["Sabastien Dyer <scdyer@uwaterloo.ca> and contributors"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PetroBase = "b72d3798-c150-44c4-b6d4-c983c975f217"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
